language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
after_success:
- julia -e 'cd(Pkg.dir("MyPkg")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
